/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.coffee_management.view.sale;

import com.java.coffee_management.model.Product;
import com.java.coffee_management.view.SaleMain;

/**
 *
 * @author Admin
 */
public class OrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetaill
     */
    private Product product;
    public OrderDetail(Product product) {
        initComponents();
        this.product = product;
        drinkName.setText(this.product.getName());
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuantity318 = new javax.swing.JPanel();
        drinkName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnMinus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnAgree318 = new javax.swing.JButton();
        btnCancel318 = new javax.swing.JButton();
        SizeComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelQuantity318.setBackground(new java.awt.Color(69, 32, 16));
        panelQuantity318.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        drinkName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        drinkName.setForeground(new java.awt.Color(255, 255, 255));
        drinkName.setText("Cà Phê Sữa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Số lượng:");

        txtQuantity.setText("1");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnMinus.setBackground(new java.awt.Color(69, 32, 16));
        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/tru(-) 318.jpg"))); // NOI18N
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(69, 32, 16));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Cong(-)318.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnAgree318.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgree318.setText("Đồng ý");
        btnAgree318.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgree318ActionPerformed(evt);
            }
        });

        btnCancel318.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel318.setText("Hủy");
        btnCancel318.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel318ActionPerformed(evt);
            }
        });

        SizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "L", "Xl" }));
        SizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Size");

        javax.swing.GroupLayout panelQuantity318Layout = new javax.swing.GroupLayout(panelQuantity318);
        panelQuantity318.setLayout(panelQuantity318Layout);
        panelQuantity318Layout.setHorizontalGroup(
            panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuantity318Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuantity318Layout.createSequentialGroup()
                        .addComponent(drinkName)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuantity318Layout.createSequentialGroup()
                        .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuantity318Layout.createSequentialGroup()
                                .addComponent(btnAgree318)
                                .addGap(71, 71, 71)
                                .addComponent(btnCancel318, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelQuantity318Layout.createSequentialGroup()
                                .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SizeComboBox, 0, 80, Short.MAX_VALUE)
                                    .addComponent(txtQuantity))
                                .addGap(71, 71, 71)
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
        );
        panelQuantity318Layout.setVerticalGroup(
            panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuantity318Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(drinkName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panelQuantity318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgree318, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel318, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQuantity318, javax.swing.GroupLayout.PREFERRED_SIZE, 348, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQuantity318, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        int quantity = Integer.parseInt(txtQuantity.getText());
        if(quantity >1)
            quantity-=1;
        txtQuantity.setText(String.valueOf(quantity));
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int quantity = Integer.parseInt(txtQuantity.getText());
        quantity+=1;
        txtQuantity.setText(String.valueOf(quantity));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAgree318ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgree318ActionPerformed
        String itemSelected = SizeComboBox.getItemAt(SizeComboBox.getSelectedIndex());
        SaleMain.fillTableOrder(product,Integer.parseInt(txtQuantity.getText()), itemSelected);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgree318ActionPerformed

    private void btnCancel318ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel318ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancel318ActionPerformed

    private void SizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SizeComboBox;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAgree318;
    private javax.swing.JButton btnCancel318;
    private javax.swing.JButton btnMinus;
    private javax.swing.JLabel drinkName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelQuantity318;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
