/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.coffee_management.view;

import com.java.coffee_management.Service.Service;

/**
 *
 * @author ASUS
 */
public class AddTable extends javax.swing.JFrame {

    /**
     * Creates new form AddTable
     */
    Service service = new Service();
    public AddTable() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanelAddTable234 = new javax.swing.JPanel();
        jPanelTabbarTable234 = new javax.swing.JPanel();
        BtnXAddtable234 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxTableFloor234 = new javax.swing.JComboBox<>();
        btnAddTable1_234 = new javax.swing.JLabel();
        btnCancelTable1_234 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelAddTable234.setBackground(new java.awt.Color(69, 32, 16));
        jPanelAddTable234.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        jPanelAddTable234.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTabbarTable234.setBackground(new java.awt.Color(153, 153, 153));
        jPanelTabbarTable234.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        BtnXAddtable234.setBackground(new java.awt.Color(255, 0, 0));
        BtnXAddtable234.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnXAddtable234.setForeground(new java.awt.Color(255, 255, 255));
        BtnXAddtable234.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnXAddtable234.setText("X");
        BtnXAddtable234.setOpaque(true);
        BtnXAddtable234.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnXAddtable234MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabbarTable234Layout = new javax.swing.GroupLayout(jPanelTabbarTable234);
        jPanelTabbarTable234.setLayout(jPanelTabbarTable234Layout);
        jPanelTabbarTable234Layout.setHorizontalGroup(
            jPanelTabbarTable234Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabbarTable234Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnXAddtable234, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTabbarTable234Layout.setVerticalGroup(
            jPanelTabbarTable234Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnXAddtable234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelAddTable234.add(jPanelTabbarTable234, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 346, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("THÊM BÀN ");
        jPanelAddTable234.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Bạn muốn đặt thêm bàn vào lầu:");
        jPanelAddTable234.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        ComboBoxTableFloor234.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LẦU 1", "LẦU 2", "LẦU 3", " " }));
        jPanelAddTable234.add(ComboBoxTableFloor234, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 87, -1));

        btnAddTable1_234.setBackground(new java.awt.Color(0, 204, 255));
        btnAddTable1_234.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddTable1_234.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTable1_234.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddTable1_234.setText("THÊM  ");
        btnAddTable1_234.setOpaque(true);
        btnAddTable1_234.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTable1_234MouseClicked(evt);
            }
        });
        jPanelAddTable234.add(btnAddTable1_234, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 175, 100, 23));

        btnCancelTable1_234.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelTable1_234.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelTable1_234.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelTable1_234.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelTable1_234.setText("HUỶ BỎ ");
        btnCancelTable1_234.setOpaque(true);
        jPanelAddTable234.add(btnCancelTable1_234, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 176, 100, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddTable234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddTable234, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnXAddtable234MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnXAddtable234MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_BtnXAddtable234MouseClicked

    private void btnAddTable1_234MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTable1_234MouseClicked
        // TODO add your handling code here:
        service.addTable(ComboBoxTableFloor234.getSelectedIndex()+1);
        this.dispose();
    }//GEN-LAST:event_btnAddTable1_234MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnXAddtable234;
    private javax.swing.JComboBox<String> ComboBoxTableFloor234;
    private javax.swing.JLabel btnAddTable1_234;
    private javax.swing.JLabel btnCancelTable1_234;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelAddTable234;
    private javax.swing.JPanel jPanelTabbarTable234;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
