/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.coffee_management.view;

import com.java.coffee_management.Service.Service;
import com.java.coffee_management.model.category;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ASUS
 */
public class EditTable extends javax.swing.JFrame {

    /**
     * Creates new form EditTable
     */
    Service service = new Service();
    public EditTable() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdittable234 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnXEdittable234 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIDtable_234 = new javax.swing.JTextField();
        jComboBoxFloor234 = new javax.swing.JComboBox<>();
        btnEditTale234 = new javax.swing.JLabel();
        btnCancelTale234 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelEdittable234.setBackground(new java.awt.Color(69, 32, 16));
        jPanelEdittable234.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        jPanelEdittable234.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        btnXEdittable234.setBackground(new java.awt.Color(255, 0, 0));
        btnXEdittable234.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXEdittable234.setForeground(new java.awt.Color(255, 255, 255));
        btnXEdittable234.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXEdittable234.setText("X");
        btnXEdittable234.setOpaque(true);
        btnXEdittable234.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXEdittable234MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnXEdittable234, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXEdittable234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelEdittable234.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 346, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("SỬA BÀN ");
        jPanelEdittable234.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID BÀN:");
        jPanelEdittable234.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("LẦU:");
        jPanelEdittable234.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 67, -1));
        jPanelEdittable234.add(jTextFieldIDtable_234, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 71, 166, -1));

        jComboBoxFloor234.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LẦU 1", "LẦU 2", "LẦU 3", " " }));
        jPanelEdittable234.add(jComboBoxFloor234, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 123, 87, -1));

        btnEditTale234.setBackground(new java.awt.Color(0, 204, 255));
        btnEditTale234.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditTale234.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTale234.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditTale234.setText("SỬA");
        btnEditTale234.setOpaque(true);
        btnEditTale234.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditTale234MouseClicked(evt);
            }
        });
        jPanelEdittable234.add(btnEditTale234, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 175, 100, 23));

        btnCancelTale234.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelTale234.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelTale234.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelTale234.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelTale234.setText("HUỶ BỎ ");
        btnCancelTale234.setOpaque(true);
        btnCancelTale234.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelTale234MouseClicked(evt);
            }
        });
        jPanelEdittable234.add(btnCancelTale234, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 176, 100, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEdittable234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEdittable234, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXEdittable234MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXEdittable234MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnXEdittable234MouseClicked

    private void btnCancelTale234MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelTale234MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelTale234MouseClicked

    private void btnEditTale234MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTale234MouseClicked
        // TODO add your handling code here:
        service.updateTable(Integer.valueOf(jTextFieldIDtable_234.getText()),Integer.valueOf(jComboBoxFloor234.getSelectedIndex()+1));
        this.dispose();
    }//GEN-LAST:event_btnEditTale234MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelTale234;
    private javax.swing.JLabel btnEditTale234;
    private javax.swing.JLabel btnXEdittable234;
    private javax.swing.JComboBox<String> jComboBoxFloor234;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEdittable234;
    private javax.swing.JTextField jTextFieldIDtable_234;
    // End of variables declaration//GEN-END:variables
}
